Added new icons
sumup-oss/circuit-ui pull request #2068
Opened 2023-04-27 12:26 UTC by oalpatov

https://sumupteam.atlassian.net/browse/IA-7306

## Purpose

Added new icons:
flip_camera, credit_note, delivery_note, electronic_invoice, recurring_invoice, no_costs

## Approach and changes

_Describe how you solved the problem_

## Definition of done

* [ ] Development completed
* [ ] Reviewers assigned
* [ ] Unit and integration tests
* [ ] Meets minimum browser support
* [ ] Meets accessibility requirements

2023-04-27 13:45 UTC, robinmetral requested changes
Thanks for making sure that this is in the Figma library! There only seems to be a small issue with some icons (those that are vertical—they should have spacing on both sides to be centered in the 24x24 box).

Can you check if you can reexport these icons by selecting the icon's group on Figma? (instead of the vector itself) 👇 

Don't do this:
<img width="564" alt="Screenshot 2023-04-27 at 15 44 46" src="https://user-images.githubusercontent.com/35560568/234881357-b37defca-bd86-4819-bd2b-2f0716c4fb91.png">

...do this:
<img width="564" alt="Screenshot 2023-04-27 at 15 44 54" src="https://user-images.githubusercontent.com/35560568/234881422-684b4137-201c-42eb-9e6e-ba0aede51010.png">

2023-04-27 13:47 UTC, robinmetral commented
Otherwise if this doesn't work let me know @oalpatov, and I'll clean them up manually 🙂

2023-04-27 14:45 UTC, robinmetral approved these changes
Looks good to me! Thanks for your contribution 🙌 🎉

2023-04-27 14:48 UTC, oalpatov commented
> Looks good to me! Thanks for your contribution 🙌 🎉

Awesome, thanks for reviewing :)

I'm wondering if there is some guide how to publish this changes? I see that I should add something to changlist (but my guess that happening after executing some command)

2023-04-27 14:51 UTC, robinmetral commented
> I'm wondering if there is some guide how to publish this changes?

You read my mind, see my reply above 🙂 The documentation is in the CONTRIBUTING.md (good place to start)—if anything is unclear let us know and we'll improve it

2023-04-27 14:53 UTC, oalpatov commented
> Ah actually a couple more things:
> 
> * you need to add a changeset so we can release the icons as a new minor for the package. Run `npm run changeset` (or refer to our contribution docs for more details)
> * since you opened the branch from a fork and not on the main repo (do you have access to the `sumup-oss` org? Otherwise I'll send you an invite) the CI is not running. Since this is an icons-only, clearly non-breaking change I'm happy to go ahead an merge it anyways. Next time please open a branch directly in `sumup-oss/circuit-ui` 🙏

I have no access to the `sumup-oss` org (the only reason why I've created a fork). Could you please send me an invite?

2023-04-28 06:28 UTC, robinmetral commented on .changeset/strong-tips-brush.md
> +Added new icons: flip_camera, credit_note, delivery_note, electronic_invoice, recurring_invoice, no_costs
```suggestion
Added new icons in size 24: `FlipCamera`, `CreditNote`, `DeliveryNote`, `ElectronicInvoice`, `RecurringInvoice`, `NoCosts`
```

2023-04-28 06:30 UTC, merged

2023-04-28 06:31 UTC, robinmetral commented
@oalpatov invite sent for joining the OSS org 🙂 

I'll handle the release for this. Congrats on your first contribution!