Add EFTPOS icon as a payment method
sumup-oss/circuit-ui pull request #2149
Opened 2023-06-06 08:58 UTC by amrdruid

Addresses Ticket: https://sumupteam.atlassian.net/browse/EPE-528

## Purpose

Add EFTPOS icon as a payment method

## Definition of done

* [ ] Development completed
* [ ] Reviewers assigned
* [ ] Unit and integration tests
* [ ] Meets minimum browser support
* [ ] Meets accessibility requirements

2023-06-06 12:43 UTC, connor-baer requested changes
Hi @amrdruid, thanks for suggesting this new icon. Before it can be added to the icon package, it needs to be added to the [Figma library](https://www.figma.com/file/LnhSTiHtYMVw3Ppw5QZVph/Circuit-UI-Foundation?type=design&node-id=2480-3476&t=uP7MCCn2henJkijs-0). Please make a request with the design team to have it added.

2023-06-06 12:43 UTC, connor-baer commented on packages/icons/manifest.json
> +    },
Please put the icon in alphabetical order, as specified in the [contribution guidelines](https://circuit.sumup.com/?path=/docs/contributing-contributing-icons--docs).

2023-06-08 15:55 UTC, connor-baer reviewed
Thanks for addressing my feedback @amrdruid. I see that the icon was added in the "[Card schemes](https://www.figma.com/file/LnhSTiHtYMVw3Ppw5QZVph/Circuit-UI-Foundation?type=design&node-id=11896%3A67&t=HDDQB5M83waAPYNb-1)" category. Its design was also adapted to match the other card scheme icons. Can you update the PR to reflect this, please?

2023-06-09 11:20 UTC, amrdruid commented
@connor-baer Thanks for catching that! I've added it now, let me know what you think

2023-06-09 15:52 UTC, connor-baer approved these changes

2023-06-09 15:56 UTC, merged