SX-2130 Allow multiple countries with same country code and styling fixes
sumup-oss/circuit-ui pull request #2586
Opened 2024-06-28 15:29 UTC by roma-claudio

Addresses SX-2130.

## Purpose

We are currently using the country code phone prefix as unique identifier of the country code select/input field. 
However the phone prefix is not unique given a list of countries (e.g. Canada and U.S. share the same country code: +1)

This PR is changing the value that is hold by the country code input/select field from the phone prefix to the country ISO code

There are also some additional styling changes included:

1. The country code field prefix is now always visible, regardless if the field is active or focused
2. The component is now taking all the space defined by the parent component, `flex-grow: 1`

## Approach and changes
Adapted the service and the component logic to consider the country code and not the phone prefix as the source of truth for the country code field and updated the css module

## Definition of done

* [ ] Development completed
* [ ] Reviewers assigned
* [ ] Unit and integration tests
* [ ] Meets minimum browser support
* [ ] Meets accessibility requirements

2024-07-18 11:22 UTC, connor-baer requested changes
I checked whether there are any countries with multiple phone codes. There doesn't seem to be any, so it appears to be a many-to-one relationship between phone code and country code. In that case, it makes total sense to use the country code as the input value. Thanks for the pull request! 🙌🏻

2024-07-18 11:22 UTC, connor-baer commented on packages/circuit-ui/components/PhoneNumberInput/PhoneNumberInput.tsx
> +        .find(({ country }) => country === selectedCountry)?.code;
The lookup uses the country ISO code, so sorting by the country code phone prefix is unnecessary.

```suggestion
      const code = countryCode.options
        .find(({ country }) => country === selectedCountry)?.code;
```

2024-07-18 11:22 UTC, connor-baer commented on packages/circuit-ui/components/PhoneNumberInput/PhoneNumberInput.tsx
> +      );
Here, the lookup is done by country code, so the sorting by length remains necessary.

```suggestion
      const pastedOption = countryCode.options
        // Match longer, more specific country codes first
      	.sort((a, b) => b.code.length - a.code.length)
        .find(({ code }) => pastedText.startsWith(code));
```

2024-10-09 08:16 UTC, connor-baer commented
@roma-claudio Do you want to address the review comments yourself, or would you mind if we take over the PR to finish it?

2024-10-09 08:19 UTC, roma-claudio commented
> @roma-claudio Do you want to address the review comments yourself, or would you mind if we take over the PR to finish it?

@connor-baer - I'm planning to work on it this Friday.

If you have a urgent deadline to be met before that I'm happy with somebody else taking it over (as I don't have capacity before)

2024-10-11 10:46 UTC, roma-claudio commented
@connor-baer - I've accepted the suggested changes 👍🏻

2024-10-15 15:37 UTC, connor-baer approved these changes
Thank you so much for the contribution, @roma-claudio! I've added a changeset which means this is good to go.

2024-10-15 15:50 UTC, merged